# Generated by Django 4.2.9 on 2026-05-10 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0002_studentpromotion"),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=20)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Percentage weight of this assessment",
                        max_digits=5,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GradeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2, help_text="Marks scored", max_digits=6
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Maximum possible marks",
                        max_digits=6,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_entries",
                        to="academics.assessmenttype",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_entries",
                        to="students.student",
                    ),
                ),
                (
                    "subject_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_entries",
                        to="academics.subjectassignment",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grade_entries",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "ordering": ["student__last_name", "assessment_type__order"],
                "unique_together": {
                    ("student", "subject_assignment", "assessment_type", "term")
                },
            },
        ),
    ]
