# Generated by Django 4.2.9 on 2026-04-08 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("promoted", "Promoted"),
                            ("repeated", "Repeated Year"),
                            ("graduated", "Graduated"),
                        ],
                        default="promoted",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("promoted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions_from",
                        to="students.academicyear",
                    ),
                ),
                (
                    "from_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions_from",
                        to="students.grade",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="students.student",
                    ),
                ),
                (
                    "to_academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions_to",
                        to="students.academicyear",
                    ),
                ),
                (
                    "to_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions_to",
                        to="students.grade",
                    ),
                ),
            ],
            options={
                "ordering": ["-promoted_at"],
            },
        ),
    ]
