# Generated by Django 4.2.9 on 2026-04-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My School", max_length=200)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                ("motto", models.CharField(blank=True, max_length=200)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school/logo/"),
                ),
                ("primary_color", models.CharField(default="#2D1B69", max_length=7)),
                ("secondary_color", models.CharField(default="#F59E0B", max_length=7)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("phone_alt", models.CharField(blank=True, max_length=30)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Rwanda", max_length=100)),
                ("po_box", models.CharField(blank=True, max_length=50)),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary School"),
                            ("secondary", "Secondary School"),
                            ("combined", "Combined School"),
                            ("university", "University / College"),
                            ("vocational", "Vocational Institute"),
                        ],
                        default="combined",
                        max_length=50,
                    ),
                ),
                (
                    "school_week_start",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        default="monday",
                        max_length=10,
                    ),
                ),
                (
                    "school_week_end",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        default="friday",
                        max_length=10,
                    ),
                ),
                (
                    "id_card_footer",
                    models.CharField(
                        blank=True,
                        default="If found, please return to the school office.",
                        max_length=200,
                    ),
                ),
                ("id_card_valid_years", models.PositiveIntegerField(default=1)),
                ("principal_name", models.CharField(blank=True, max_length=200)),
                (
                    "principal_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="school/signatures/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Profile",
                "verbose_name_plural": "School Profile",
            },
        ),
    ]
