# Generated by Django 4.2.9 on 2026-04-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolprofile",
            name="primary_color",
            field=models.CharField(blank=True, default="#2D1B69", max_length=7),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="secondary_color",
            field=models.CharField(blank=True, default="#F59E0B", max_length=7),
        ),
    ]
