# Generated by Django 4.2.9 on 2026-04-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_schoolprofile_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolprofile",
            name="id_card_show_photo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="id_card_footer",
            field=models.CharField(
                blank=True,
                default="If found please return to school office",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="id_card_valid_years",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of years the ID card is valid"
            ),
        ),
        migrations.AlterField(
            model_name="schoolprofile",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Official school registration number",
                max_length=100,
            ),
        ),
    ]
